function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    params(12)=params(6)/(1-params(4));
    params(10)=(params(4)*params(1)/params(6))^(1/(1-params(1)))-params(8);
    params(9)=params(3)-params(10)*params(2);
    params(11)=params(9)*params(4)*params(12);
    params(14)=1/params(2)*(params(6)*params(9)+params(2)*(params(8)+params(10))^params(1));
    params(16)=(params(6)*(params(5)-1)+params(5)*params(7))/(params(6)*(1-params(5)));
    params(15)=params(7)*params(5)*(params(4)-params(5))/(params(6)*(1-params(5)));
    params(13)=params(9)*params(7);
    Css=params(13)+params(2)*params(14);
    Yss=Css;
    % Auxiliary equations
end
